ami_id: "ami-0abcdef1234567890"
instance_type: "t3.medium"
key_name: "clickhouse-key"
security_group_id: "sg-0123456789abcdef0"
subnet_id: "subnet-0abcdef1234567890"
backup_policy: "multi-az"
volume_size: 50  # EBS volume size in GB
